# Project: ProgramaCalculadora
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Calculadora.o
LINKOBJ  = Calculadora.o
LIBS     = -L"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/lib" -L"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/include" -I"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/include" -I"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/penie/Desktop/PAHOLA/PROGRAMACIÓN/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ProgramaCalculadora.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Calculadora.o: Calculadora.cpp
	$(CPP) -c Calculadora.cpp -o Calculadora.o $(CXXFLAGS)
